Traceback (most recent call last):
  File "train.py", line 49, in <module>
    main()
  File "train.py", line 46, in main
    trainer.test(model, DataLoader(test_set), batch_size = batch_size)
TypeError: test() got an unexpected keyword argument 'batch_size'